Main.class: browserlexer.class Main.java
	javac Main.java
browserlexer.class: browserlexer.java
	javac browserlexer.java
browserlexer.java: browserlexer
	java -cp JLex2.jar JLex2.Main browserlexer
clean:
	rm -f *.class browserlexer.java